language: go

go:
  - tip

script:
  - go build github.com/willeponken/elvisp/cmd/elvispd
  - go build github.com/willeponken/elvisp/cmd/elvispc
  - go test $(go list github.com/willeponken/elvisp/...)
